CREATE TABLE DM_LOGIN (
USERNAME VARCHAR PRIMARY KEY,
PASSWORD VARCHAR,
STATUS VARCHAR(50)
);
/
CREATE TABLE DM_OTP (
USERNAME VARCHAR PRIMARY KEY,
OTP VARCHAR
);
/
CREATE TABLE DM_CUSTOMER (
USERNAME VARCHAR PRIMARY KEY,
NAME VARCHAR,
EMAIL VARCHAR,
MOBILE VARCHAR
)
/
CREATE TABLE DM_ITEM (
ITEM_ID VARCHAR(150) PRIMARY KEY,
ITEM_NAME VARCHAR(150),
ITEM_CAT VARCHAR(150),
ITEM_SUB_CAT VARCHAR(150),
URL VARCHAR(150),
PRICE DECIMAL,
QUANTITY NUMBER,
OFFER DECIMAL,
EXPIRY_DATE DATE,
VENDOR VARCHAR(150)
);
/
stop
/