CREATE TABLE DM_LOGIN (
USERNAME VARCHAR PRIMARY KEY,
PASSWORD VARCHAR,
STATUS VARCHAR(50)
);
/
CREATE TABLE DM_OTP (
USERNAME VARCHAR PRIMARY KEY,
OTP VARCHAR
);
/
CREATE TABLE DM_CUSTOMER (
USERNAME VARCHAR PRIMARY KEY,
NAME VARCHAR,
EMAIL VARCHAR,
MOBILE VARCHAR
)
/
stop
/